using System.ComponentModel.DataAnnotations;

namespace WebAPI.Dtos.NationalMinority
{
	/// <summary>
	/// Used to create a new NationalMinority.
	/// Only the Name is required; Id is generated by the DB.
	/// </summary>
	public class NationalMinorityCreateDto
	{
		[Required]
		[StringLength(100)]
		public string Name { get; set; }
	}
}
