using System.ComponentModel.DataAnnotations;

namespace WebAPI.Dtos.NationalMinority
{
    /// <summary>
    /// DTO used to create a new NationalMinority.
    /// Only the Name is required; Id is generated by the database.
    /// </summary>
    public class NationalMinorityCreateDto
    {
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(100, ErrorMessage = "Name must not exceed 100 characters.")]
        public string Name { get; set; } = string.Empty;
    }
}
